name: pages build and deployment

on:
  push:
    branches:
      - main
      - main-forcada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'false'
      # Adicione aqui os outros steps necessários para build/deploy do seu projeto
